### ISSUE TITLE
having a scrollview on the error boundary

### ISSUE THREAD

**Issue by zcaudate** [carloscuesta/react-native-error-boundary#162]
sometimes, there is an error and the debug information is too long for the `GO BACK` button to display.

It would be great if there was a scrollview so I can scroll down.

<img width="337" alt="Screen Shot 2021-08-03 at 1 04 25 pm" src="https://user-images.githubusercontent.com/1455572/127960685-7d30c4c3-8204-4c4e-88a1-22e565138c5c.png">

**Comment by carloscuesta** [comment]
Hey @zcaudate this can be implemented using the `FallbackComponent` prop in the `ErrorBoundary` component:

You can read it here: https://github.com/carloscuesta/react-native-error-boundary#errorboundary 😊

**Comment by zcaudate** [comment]
okay. that makes sense. Thanks for the link.
