### ISSUE TITLE
[BUG] FallbackComponent crashing Android App

### ISSUE THREAD

**Issue by bombillazo** [carloscuesta/react-native-error-boundary#220]
### Problem

Hello. This has been a tough one to debug. 

When using the `react-native-error-boundary` component with a FallBackComponent prop, running the installed app on an Android device causes an app crash. It only happens on the _installed_ app. I am able to run the app locally with RN commands and connect to the RN server, the app runs normally. But once the app is built (assembled) and installed on an Android device, opening a screen with an error boundary component that uses FallbackComponent makes the app crash. ErrorBoundary without fallback works as expected. This is the Android Crash error:
```sh
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
This error is located at: in Unknown in RCTView in Unknown in RNCSafeAreaView in RNBareErrorHandler in ErrorBoundary in App in RCTView in Unknown in RCTView in Unknown in AppContainer, js engine: hermes, stack: S@1:1312420 anonymous@1:1313739 anonymous@1:1513434 renderWithHooks@1:135810 updateForwardRef@1:140618 beginWork$1@1:174318 performUnitOfWork@1:161376 workLoopSync@1:161234 renderRootSync@1:161118 performSyncWorkOnRoot@1:158493 flushSyncCallbacks@1:126101 flushPassiveEffects@1:163450 anonymous@1:162428 V@1:280824 w@1:281146 anonymous@1:196283 _callTimer@1:195522 callTimers@1:197360 __callFunction@1:102589 anonymous@1:101078 __guard@1:102035 callFunctionReturnFlushedQueue@1:101036 
```
React Error #321 is [this one](https://reactjs.org/docs/error-decoder.html/?invariant=321):
```error
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
Taking out the ErrorBoundary FallbackComponent prop makes the installed app work. On the error itself, I have compatible React and React Native libs to use hooks so doubt it is reason 1. My suspicion is this either the FallbackComponent seems to be tripping React dependencies and importing React twice *_OR_* the library is using hooks in an invalid way internally and for some reason only during an install build does the app detect and crash.

### Example Code

```tsx
import React, { useState } from 'react';
import { View, Text, Button, SafeAreaView } from 'react-native';
import ErrorBoundary from 'react-native-error-boundary'

const CustomFallback = (props: { error: Error, resetError: Function }) => (
  <View>
    <Text>Something happened!</Text>
    <Text>{props.error.toString()}</Text>
    <Button onPress={props.resetError}>Restart</Button>
  </View>
)

const ComponentWithError  = () => {
  throw Error("This component errors out");
  return <View />;
}

export const App = () => {
  const [isErrorComponentVisible, setIsErrorComponentVisible] = useState(false);
  // Wrap the app in an error boundary to catch any errors
  return (
    <ErrorBoundary FallbackComponent={CustomFallback}>
      <SafeAreaView style={{ flex: 1 }}>
        <Text>Test</Text>
        <Button onPress={() => setIsErrorComponentVisible(true)}>
          Throw error
        </Button>
        {isErrorComponentVisible && <ComponentWithError />}
      </SafeAreaView>
    </ErrorBoundary>
  );
};
```

### Versions
React - "17.0.2"
React Native - "0.66.4"
React Native Error Boundary - "^1.1.12"

**Comment by carloscuesta** [comment]
Hey! Thanks for the detailed report.

I'm sorry to hear that you had a tough one debugging this error but I'm not 100% sure that the error is related with this library for the following reasons:

There's [not a single hook call](https://github.com/carloscuesta/react-native-error-boundary/search?q=useEffect) on the `react-native-error-boundary` library, so we can't break the rules of hooks if we're not using them.

The library does not include any `dependency` as you can see in the `package.json`, we just define the `peerDependencies` and nothing else:

https://github.com/carloscuesta/react-native-error-boundary/blob/4b0fb7752f552b1ee3b0949b057565da86017cb6/package.json#L68

https://github.com/carloscuesta/react-native-error-boundary/blob/4b0fb7752f552b1ee3b0949b057565da86017cb6/package.json#L47-L50

> Taking out the ErrorBoundary FallbackComponent prop makes the installed app work.

Can you please provide an isolated reproduction case the error happens so I can reproduce it and try to fix it? 

Thanks 🙏🏼

**Comment by bombillazo** [comment]
Hello, thanks for the quick response! Glad to know those factors about the library.

The interesting thing is that it still fails with a very bare custom FallbackComponent, like the one in my example. I also colocated the component in the same file to make sure it wasn't some random import issue.
```tsx
const CustomFallback = (props: { error: Error, resetError: Function }) => (
  <View>
    <Text>Something happened!</Text>
    <Text>{props.error.toString()}</Text>
    <Button onPress={props.resetError}> fsdfsdf</Button>
  </View>
)
```
This fallback component would also cause the error, but again it only happens on a bundled/built and installed app. I'll try to have  a "working demo" to reproduce the error soon.

**Comment by carloscuesta** [comment]
🤔 Interesting, I don't have a real Android device to test, but I built an expo snack with a `FallbackComponent`, can you try to install this https://snack.expo.dev/@carloscuesta/react-native-error-boundary-fallbackcomponent and see if you can reproduce the problem?

**Comment by carloscuesta** [comment]
Hey @bombillazo 

I was taking a look at your code again and not sure if that could be what's breaking your app, but if you take a look at my Expo example the error throw is done inside a `useEffect`

You're not wrapping your `throw Error` in your `ComponentWithError` example

https://snack.expo.dev/@carloscuesta/react-native-error-boundary

**Comment by bombillazo** [comment]
Hey @carloscuesta 

Thanks for the effort, I recently solved this (finally!) and it was unrelated to this library, fortunately! It had to do with the bundling process while running in Github Actions. 🤦 All works as expected now. This can be closed :)

**Comment by carloscuesta** [comment]
Hey! @bombillazo no problem, happy to hear that 😊
