### ISSUE TITLE
The errors in released version iOS return Native compiled index bundle file stacktrace instead

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [carloscuesta/react-native-error-boundary#34]
The errors in released version iOS return Native compiled index bundle file stacktrace instead. Anyways to get actual js file detail

**Comment by carloscuesta** [comment]
This is correct. That's what React-Native returns since the bundle is compiled. If you want to get the whole stacktrace instead you should use and upload sourcemaps to your reporting service
