### ISSUE TITLE
Display stack trace on RELEASE build

### ISSUE THREAD

**Issue by Koxx3** [carloscuesta/react-native-error-boundary#514]
### Describe the bug

Hello,

is it possible to display the stack trace when built in release ?
if yes, how ?

Regads,
F.

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/react-native-error-boundary/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Yes, but it should be implemented in your application not as part of your library, read more why here: 

https://github.com/carloscuesta/react-native-error-boundary/issues/315#issuecomment-1162414138
