### ISSUE TITLE
How to get stackTrace info in FallbackComponent?

### ISSUE THREAD

**Issue by l2aelba** [carloscuesta/react-native-error-boundary#601]
### Description of the question

I  know we can do…

```html
<ErrorBoundary
   FallbackComponent={MyErrorPage}
   onError={(error: Error, stackTrace: string) =>{ console.log(stackTrace) }}
>
   …
</ErrorBoundary>
```

But does it possible to get `stackTrace` info in `MyErrorPage` (FallbackComponent) by using `props` or something?

I don't want to do something about this outside `MyErrorPage` (FallbackComponent) sorry.

Thanks.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [FAQ](https://react-native-error-boundary.js.org/faq)
- [X] Check that there isn't [already an issue](https://github.com/carloscuesta/react-native-error-boundary/issues?q=is%3Aissue) asking the same question.

**Comment by carloscuesta** [comment]
Hey! @l2aelba 

Thanks for opening an issue, it's not possible to access the `stackTrace` outside of the scope of the `onError` function.

https://github.com/carloscuesta/react-native-error-boundary/blob/9683596970ced546b93e346494efd8d60fdd7bf2/src/ErrorBoundary/index.tsx#L10

The `FallbackComponent` only receives two props, `error` and `resetError` as you can see here:

https://github.com/carloscuesta/react-native-error-boundary/blob/9683596970ced546b93e346494efd8d60fdd7bf2/src/ErrorBoundary/index.tsx#L42-L45

> I don't want to do something about this outside MyErrorPage (FallbackComponent) sorry.

Not sure if I follow this, can you elaborate a bit more what you're trying to achieve? 

Usually the `stackTrace` shouldn't be exposed to your end users, it's something you should internally keep logged in your system. Therefore I don't think we should pass that to the `FallbackComponent`, given that you can capture it in the `onError` callback.
