### ISSUE TITLE
Android release app crashes!

### ISSUE THREAD

**Issue by erie-e9** [carloscuesta/react-native-error-boundary#716]
### Describe the bug

Hey, first thanks for useful library. 
Trying to integrate it to my (no Expo) project but instead of getting expected behavior app is just crashing. Before create this bug I ensured test another fixes suggested in another repo issues.
Basically I'm following the next link provided example in a signed apk file.
https://snack.expo.dev/@carloscuesta/react-native-error-boundary?platform=android

Evidence 
![gif](https://github.com/carloscuesta/react-native-error-boundary/assets/6515342/b02468fe-5ba6-49bd-941c-cf72406ee11e)

### Reproduction

Using: onPress={() => throw new Error('I am an error')}

Possible fixes already tested but not luck:
-The button that that is throwing the error is a children of the ErrorBoundary component? Yes, pretty sure.
-Are I on DEV env? No, I created a signed APK file to test it.
-Tested it with/without pass `FallbackComponent`? Yes, both cases app crashes.
-Only happens on Android platform? I only tested it on real Android device, but also happens on emulator/simulator, I cannot provide info using real iOS device.
-ErrorBoundary tag is wrapping correctly? Yup, is wrapping it in src/App.tsx file
-Did I review next image with possible errors? Yes, not luck
![image](https://user-images.githubusercontent.com/7629661/194494135-c7890121-e7b7-4591-882c-fc3f24dd1541.png)
Please, let me know if there exist another way to generate a happy to test it

Links I followed:
https://github.com/carloscuesta/react-native-error-boundary/issues/95
https://snack.expo.dev/@carloscuesta/react-native-error-boundary?platform=android

### System Info

```Shell
react version 18.2.0
react-native version 0.72.6
react-native-error-boundary 1.2.3
typescript 5.2.2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/react-native-error-boundary/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Hey! 👋🏼 

The issue is that you're throwing an error inside of an event handler `onPress`. As the React documentation says (the screenshot that you pasted), there's a point that says:

> Error boundaries do **not** catch errors for:
> Event handlers

Read more about it here:

https://legacy.reactjs.org/docs/error-boundaries.html#how-about-event-handlers

In case you want to check the rendering of the fallback component, please use any of the examples provided in the documentation _(we're not throwing any error inside an event handler)_

https://react-native-error-boundary.js.org/usage/recovering-errors

**Comment by carloscuesta** [comment]
Related with #95 & https://github.com/carloscuesta/react-native-error-boundary/issues/403
