### ISSUE TITLE
Difference with react-error-boundary?

### ISSUE THREAD

**Issue by ianbayne** [carloscuesta/react-native-error-boundary#82]
Hi, this looks like a great option! I'm a bit confused as to what the difference is with [`react-error-boundary`](https://github.com/bvaughn/react-error-boundary). Perhaps the README can lay out the differences and explain why someone might choose one over the other?

**Comment by carloscuesta** [comment]
Hello @ianbayne 

Let me explain myself,

The main difference is that `react-native-error-boundary` targets `react-native`. It provides a default `FallbackComponent` that uses `react-native` components underneath, so this is **not compatible with react** on the web. 

As I can see the API is a little bit different `react-error-boundary` has a lot of more options built in and I'm pretty sure you can use it aswell with `react-native`.

I would say that you pick the option you most like based on your needs and on the API that both libraries provide 👍🏼

**Comment by carloscuesta** [comment]
Let me know if you need something else 😊

**Comment by ianbayne** [comment]
Thank you very much for the explanation! Do you mind if I add the above information to the README in a PR?

**Comment by carloscuesta** [comment]
Yes you can add the information if you want below the demo section. 😊
